[package]
name = "mail-send"
description = "E-mail delivery library with SMTP and DKIM support"
version = "0.2.1"
edition = "2018"
authors = [ "Stalwart Labs <hello@stalw.art>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stalwartlabs/mail-send"
homepage = "https://github.com/stalwartlabs/mail-send"
keywords = ["smtp", "dkim", "email", "mime", "mail"]
categories = ["email"]
readme = "README.md"

[lib]
doctest = false

[dependencies]
mail-builder = "0.2.1"
base64 = "0.13"
rand = {version = "0.8.5", optional = true}
md5 = {version = "0.7.0", optional = true}
rsa = {version = "0.6.1", optional = true}
sha2 = {version = "0.10.2", optional = true}
tokio = { version = "1.16", features = ["net", "io-util", "time"]}
rustls = { version = "0.20", features = ["dangerous_configuration"]}
tokio-rustls = { version = "0.23.4"}
webpki-roots = { version = "0.22.3"}
gethostname = { version = "0.2.2"}

[dev-dependencies]
tokio = { version = "1.16", features = ["net", "io-util", "time", "rt-multi-thread", "macros"] }

[features]
default = [ "digest-md5", "cram-md5", "dkim"] 
digest-md5 = ["md5", "rand"]
cram-md5 = ["md5"]
dkim = ["rsa", "sha2"]
